- core/host-mock.js
- core/leviate.config.js
- documentation/docs/getting-started.md
> chore: move proxy url to env variable

- CHANGELOG.md
- core/concreteOptions.js
- core/entry.js
- core/host-mock.js
- core/store/index.js
- core/store/message.js
- package-lock.json
- package.json
- template/project/package.json
- add support for put and delete methods
> fix: authorizedGetRequest

- .github/workflows/release-please.yml
Node 12 (v1) now deprecated. Bumped to use v2
> fix: bump node version in release-please

- core/components/layout/project/LvVersionsDev.vue
Error found with localState undefined. Refactored to use useVersions composable.
> fix: version save bug fixed

- .github/workflows/release-please.yml
- core/components/layout/project/LvVersionsDev.vue
release please node version update
> Dcic 283 error saving version

- core/components/layout/input/LvInputContent.vue
Added overflow class to allow scrollbars when needed
> fix: added overflow auto to input panel

- core/components/ui/LvPanel.vue
> fix: defer window resize event when toggling panels

- core/components/layout/project/info/LvProjectInfo.vue
- core/server/manifestPlugin.js
- template/project/src/mock.config.js
- fix manifest and updates json in dev environment
> fix: align mock config and LvProjectInfo.vue with LDS data structure

- app/.npmrc
- core/components/layout/LvLayout.vue
- core/components/layout/LvReadOnlyBanner.vue
- core/store/index.js
- template/project/src/locales/en.js
> chore: add read-only banner

- core/concreteOptions.js
fix: restore the fix in [PR #148](https://github.com/leviat-tech/leviate/pull/148)
> show correct error messages for array items

- core/models/CoreLayerModel.js
- core/models/CorePositionModel.js
Reverts leviat-tech/leviate#180
> Revert "Clone"

- core/components/layout/project/LvProjectPanelItem.vue
https://crhleviat.atlassian.net/browse/CIC-551
> fix: keep one tab always open

- core/createApp.js
Reverts leviat-tech/leviate#199
> Revert "feat: enable setting locale from host selected language"

- core/components/ui/LvPopupMenu.vue
[HIT-234](https://crhleviat.atlassian.net/browse/HIT-234)
[HIT-234]: https://crhleviat.atlassian.net/browse/HIT-234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: layers pop-up window's position

- core/BaseModel.ts
Reverts leviat-tech/leviate#223
> Revert "feat: add generic category getErrorByPath to BaseModel"

- core/BaseModel.ts
in scope of [SPA-400](https://crhleviat.atlassian.net/browse/SPA-400)
[SPA-400]: https://crhleviat.atlassian.net/browse/SPA-400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add type as an create error arg; add createErrMsg alias

- core/BaseModel.ts
[SPA-400](https://crhleviat.atlassian.net/browse/SPA-400)
[SPA-400]: https://crhleviat.atlassian.net/browse/SPA-400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: switch to error message for validate func

- CHANGELOG.md
- package-lock.json
- package.json
Reverts leviat-tech/leviate#234
> Revert "chore(main): release 5.13.0"

- core/BaseModel.ts
Reverts leviat-tech/leviate#233
> Revert "feat: switch to error message for validate func"

- core/composables/useApiGateway.ts
- core/getSharedConfig.js
- core/server/authPlugin.js
- package-lock.json
- package.json
- template/project/package.json
- Ensure auth plugin is active in preview env for e2e testing 
- Add plugin id to API gateway request headers
> Auth updates

- core/composables/useShapeSelect.js
- core/extensions/pdfFormatter.js
Extract and expose column data into data object and put annotations and title in it
> feat: extract column data

- core/components/import/LvImportShapeItem.vue
- core/composables/useShapeSelect.js
> Pdf openings detection

- core/BaseModel.ts
[SPA-476](https://crhleviat.atlassian.net/browse/SPA-476)
[SPA-476]: https://crhleviat.atlassian.net/browse/SPA-476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add validation error params support

- core/composables/useVersions.js
- core/host-mock.js
> fix: versions

- core/drawing/components/DViewport.vue
1. Expose zoomTo function
2. Convert params to support TS
> fix: expose zoomTo

- core/drawing/components/popup/DPopupDimensionAxis.vue
emit additionally difference and axis info on axis dims change to provide more flexible update of the vertices (in scope of [LA-215](https://crhleviat.atlassian.net/browse/LA-215))
[LA-215]: https://crhleviat.atlassian.net/browse/LA-215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: emit additional info on dims axis update

- core/createApp.js
- package-lock.json
- package.json
Logic required for https://crhleviat.atlassian.net/browse/LA-164. I decided to include it here to avoid having to install it separately in each project.
> chore: add toast composable
